/**
 * projects.ts
 *
 * Project portfolio loaded from extracted-projects.json (generated by
 * `npm run extract` against the WordPress Samples page; 58 projects as
 * of 2026-07-14). Fallback seed data was removed in favor of the full
 * extraction output.
 */

import extractedProjects from './extracted-projects.json';
import type { ProjectDetail } from '@/src/types';

/* ── Data ─────────────────────────────────────────────────────── */

/**
 * The extraction pass produced two entries whose sanitized titles
 * collapsed to the same slug (pauma-travel-center). Keep both entries
 * but give the second a unique slug so /projects/[slug] routes never
 * collide.
 */
function dedupeSlugs(list: ProjectDetail[]): ProjectDetail[] {
  const seen = new Map<string, number>();
  return list.map((p) => {
    const count = seen.get(p.slug) ?? 0;
    seen.set(p.slug, count + 1);
    return count === 0 ? p : { ...p, slug: `${p.slug}-${count + 1}` };
  });
}

const projects: ProjectDetail[] = dedupeSlugs(
  extractedProjects.projects as ProjectDetail[],
);

/* ── Exports ─────────────────────────────────────────────────── */

export function getProjectBySlug(slug: string): ProjectDetail | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getAllProjects(): ProjectDetail[] {
  return [...projects];
}

export function getFeaturedProjects(currentSlug: string): ProjectDetail[] {
  return projects.filter((p) => p.slug !== currentSlug).slice(0, 4);
}

export type { ProjectDetail };